INSERT INTO weighting_factor (name, weighting_factor)
VALUES ('HIGHEST', 11),
       ('VERY HIGH', 10),
       ('HIGH', 9),
       ('LOW HIGH', 8),
       ('LOWEST HIGH', 7),
       ('AVERAGE', 6),
       ('HIGHEST LOW', 5),
       ('HIGH LOW', 4),
       ('LOW', 3),
       ('VERY LOW', 2),
       ('LOWEST', 1);

INSERT INTO common_personal_data (description)
VALUES ('honesty'),
       ('responsibility'),
       ('mental health'),
       ('balance'),
       ('ability to control oneself'),
       ('sensitivity'),
       ('friendly attitude to others'),
       ('optimistic outlook on life'),
       ('self-confidence'),
       ('sociability'),
       ('desire to communicate'),
       ('stress resistance'),
       ('charisma'),
       ('interest in people'),
       ('organization'),
       ('purposefulness'),
       ('ambition'),
       ('justice');

INSERT INTO common_professional_data (description)
VALUES ('experience as a project manager for more than a year'),
       ('experience as a business analyst for more than a year'),
       ('experience as a systems analyst for more than a year'),
       ('more than a year of experience in front-end development'),
       ('more than a year of experience in back-end development'),
       ('more than a year of experience in full stack development'),
       ('more than a year of experience in DB development'),
       ('more than a year of experience in DB development'),
       ('ability to plan their activities, knowledge of time management'),
       ('desire for self-improvement'),
       ('critical perception and the ability to rethink situations and the surrounding reality'),
       ('erudition'),
       ('ability to teach others'),
       ('openness to everything new, the ability to look for new forms and methods of work'),
       ('ability to work in a team'),
       ('ability to support and ignite people with a new idea'),
       ('ability to create a working team with a favorable psychological atmosphere for work'),
       ('ability to manage people, the desire to lead people, to jointly achieve goals'),
       ('ability to distribute attention, keep in mind the tasks of different orientations'),
       ('logical and critical thinking'),
       ('initiative'),
       ('efficiency in resolving emerging issues'),
       ('ability to identify priority goals and objectives'),
       ('desire to succeed at any cost');